<section class="container">
  <h1>THIS IS THE ADMIN HOME PAGE</h1>
</section>

<section class="container">
  <ul id="errorList" class="errorList">
  </ul>
</section>

<br /><br />
<section class="container">
  <form class="form-container">
    <div class="form-wrapper">
      <div class="form-group-stretch">
        <label for="email">Email : </label>
        <input type="text" name="email" id="email" />
      </div>
    </div>
    <div class="form-wrapper">
      <div class="form-group-stretch">
        <label for="psw">Password : </label>
        <input type="text" name="psw" id="psw" />
      </div>
    </div>
    <div class="form-wrapper">
      <div class="form-group-stretch">
        <button id="btn" type="button" class="btn-boston-stretch" style="text-transform: uppercase"
          onclick="checkUser()">
          <?= $trans['user']['btn']['login'] ?>
        </button>
      </div>
    </div>
  </form>
</section>