<!DOCTYPE html>
<html lang="<?= $scMetaLanguage ?>" dir="ltr" color-scheme="auto">

<head>
  <?php include 'backend/header.phtml'; ?>



  <link rel="stylesheet" href="<?= $scPathCoreCss; ?>.css">
  <link rel="stylesheet" href="<?= $scPathTempCss; ?>.css">
  <link rel="stylesheet" href="<?= $scPathCss; ?>.css">
</head>

<body onload="runOnLoad()">
  <div class="grid-full-layout">
    <header>
      <?php include 'backend/navigation.phtml' ?>
    </header>

    <div class="page">
      <aside>
        <?php include 'backend/sidebar.phtml' ?>
      </aside>
      <main>
        <section class="breadcrumbs">
          <?php foreach ($breadcrumbs as $key => $value): ?>
          <a href="#" onclick="btnPostRedirect('<?= $value ?>')"><?= $key ?></a>
          <?php endforeach ?>
        </section>

        <section class="errorhandler">
          <ul id="errorList" class="errorList">
          </ul>
        </section>

        <?php include $page; ?>
      </main>
    </div>


    <footer>
      <?php include 'backend/footer.phtml' ?>
    </footer>
  </div>


  <script type="module" src="<?= $scPathCoreJs; ?>.js"></script>
  <script src="<?= $scPathTempJs; ?>.js"></script>
  <script src="<?= $scPathJs; ?>.js"></script>
</body>

</html>