services:
  #nginx
  server:
    container_name: scode-server
    image: nginx:stable-alpine
    restart: always
    ports:
      - "7080:80"
    volumes:
      - ../html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scodenet

  #php
  app:
    container_name: scode-app
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../html:/var/www/html
    networks:
      - scodenet

networks:
  scodenet:
    name: scodenet
