services:
  #nginx
  scodeserver:
    container_name: scodeserver
    image: nginx:stable-alpine
    restart: always
    ports:
      - "7080:80"
      - "7082:82"
      - "7084:84"
    volumes:
      - ../html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scodenet

  #app -- https://example.org
  scodeapp:
    container_name: scodeapp
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../html:/var/www/html
    networks:
      - scodenet

  #admin -- https://admin.example.org
  scodeadmin:
    container_name: scodeadmin
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../html:/var/www/html
    networks:
      - scodenet

  #api -- https://api.example.org
  scodeapi:
    container_name: scodeapi
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../html:/var/www/html
    networks:
      - scodenet

  #dB
  scodedb:
    container_name: scodedb
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 7086:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - scodedata:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: scodeblog
      MYSQL_USER: admin
      MYSQL_PASSWORD: r00tadmin
      MYSQL_ROOT_PASSWORD: r00tadmin
    networks:
      - scodenet

  #phpadmin
  scodedbadmin:
    container_name: scodedbadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: scodedb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 7088:80
    networks:
      - scodenet

volumes:
  scodedata:
    driver: local
    name: scodedata

networks:
  scodenet:
    name: scodenet
