<meta charset="<?= $scMetaCharset ?>">
<meta name="google-site-verification" content="<?= $scMetaGoogleSiteVerification ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="<?= $scMetaDescription ?>">
<meta name="Keywords" content="<?= $scMetaKeywords ?>">
<meta name="Copyright" content="<?= $scMetaOgSiteName ?>">
<!--Facebook-->
<meta property="og:site_name" content="<?= $scMetaOgSiteName ?>">
<meta property="og:url" content="<?= $scMetaOgUrl ?>">
<meta property="og:type" content="<?= $scMetaOgType ?>">
<meta property="og:title" content="<?= $scMetaOgTitle . '|' . $scMetaOgSiteName ?> " />
<meta property=" og:description" content="<?= $scMetaOgDescription; ?>">
<!--Next image => SGV file is best scalable-->
<meta property="og:image" content="<?= $scMetaOgImage ?>">
<!--Twitter meta-->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="<?= $scMetaDescription ?>" />
<meta name="twitter:title" content="<?= $scMetaOgTitle . '|' . $scMetaOgSiteName ?> " />
<meta name="twitter:site" content="<?= $scTwitterSite; ?>" />
<meta name="twitter:domain" content="<?= $scTwitterDomain ?>" />
<meta name="twitter:image" content="<?= $scMetaOgImage; ?>" />
<meta name="twitter:creator" content="<?= $scTwitterSite; ?>" />
<!--PintRest meta-->
<meta name="p:domain_verify" content="<?= $scPintRestKey; ?>" />

<!--Favicon meta-->
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/scorpio-apple-180x180.png">
<link rel="icon" type="image/png" sizes="512x512" href="/favicon/scorpio-512x512.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicon/scorpio-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon.ico">
<link rel="manifest" href="/favicon/manifest.json">

<!-- No caching -->
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />

<title><?= $scMetaOgTitle . " | " . $scMetaOgSiteName ?></title>

<link rel='icon' href='data:,' />