<div class="wrapper">
  <div class="dropdown">
    <button class="dropdown-btn" onclick="toggleDropDown(event)">
      <span><?= $trans['sidebar']['dashboard'] ?></span>
      <span class="arrow"></span>
    </button>
    <ul class="dropdown-content">
      <li>
        <a <?= $scMetaController === 'Dashboard' ? 'class="active"' : '' ?> href="#"
          onclick="btnPostRedirect('/<?= $scMetaLanguage ?>/dashBoard')">
          <?= $trans['sidebar']['dashboard'] ?>
        </a>
      </li>
    </ul>
  </div>
</div>

<div class="wrapper">
  <div class="dropdown">
    <button class="dropdown-btn" onclick="toggleDropDown(event)">
      <span><?= $trans['sidebar']['users'] ?></span>
      <span class="arrow"></span>
    </button>
    <ul class="dropdown-content">
      <li>
        <a <?= $scMetaController === 'User' ? 'class="active"' : '' ?> href="#"
          onclick="btnPostRedirect('/<?= $scMetaLanguage ?>/user/readall')">
          <?= $trans['sidebar']['list'] ?>
        </a>
      </li>
      <?php if ($data['realm'] === 'super'): ?>
        <li>
          <a <?= $scMetaController === 'User' ? 'class="active"' : '' ?> href="#"
            onclick="btnPostRedirect('/<?= $scMetaLanguage ?>/user/create')">
            <?= $trans['sidebar']['create'] ?>
          </a>
        </li>
      <?php endif ?>
    </ul>
  </div>
</div>

<div class="wrapper">
  <div class="dropdown">
    <button class="dropdown-btn" onclick="toggleDropDown(event)">
      <span><?= $trans['sidebar']['posts'] ?></span>
      <span class="arrow"></span>
    </button>
    <ul class="dropdown-content">
      <li>
        <a <?= $scMetaController === 'Post' ? 'class="active"' : '' ?> href="#"
          onclick="btnPostRedirect('/<?= $scMetaLanguage ?>/post/readall')">
          <?= $trans['sidebar']['list'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'Post' ? 'class="active"' : '' ?> href="#"
          onclick="btnPostRedirect('/<?= $scMetaLanguage ?>/user/create')">
          <?= $trans['sidebar']['create'] ?>
        </a>
      </li>
    </ul>
  </div>
</div>