<nav class="navbar">
  <div class="brand-title">
    <?= $scMetaOgSiteName ?>
  </div>

  <a href="#" class="toggle-button">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
  </a>
  <div class="navbar-links">
    <ul class="links">
      <li>
        <a <?= $scMetaController === 'Home' ? 'class="active"' : '' ?> href="/<?= $scMetaLanguage ?>/Home">
          <?= $trans['nav']['home'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'About' ? 'class="active"' : '' ?> href="/<?= $scMetaLanguage ?>/About">
          <?= $trans['nav']['about'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'Contact' ? 'class="active"' : '' ?> href="/<?= $scMetaLanguage ?>/Contact">
          <?= $trans['nav']['contact'] ?>
        </a>
      </li>
    </ul>

    <!-- <ul class="links-lang">
      <li><a <?= $scMetaLanguage === 'en' ? 'class="active"' : '' ?> href="/en/<?= $scMetaRoute ?>">En</a>
      </li>
      <li>
        <a <?= $scMetaLanguage === 'nl' ? 'class="active"' : '' ?> href="/nl/<?= $scMetaRoute ?>">Nl</a>
      </li>
      <li><a <?= $scMetaLanguage === 'fr' ? 'class="active"' : '' ?> href="/fr/<?= $scMetaRoute ?>">Fr</a></li>
    </ul> -->
    <!-- <div style="display: flex; padding: 0.5rem">
        <select id="theme" class="selectTheme">
          <option value="auto" selected>Theme</option>
          <option value="light">Light</option>
          <option value="dark">Dark</option>
        </select>
      </div> -->
  </div>
</nav>