<meta charset="<?= $scMetaCharset ?>">
<meta name="google-site-verification" content="<?= $scMetaGoogleSiteVerification ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="<?= $scMetaDescription ?>">
<meta name="Keywords" content="<?= $scMetaKeywords ?>">
<meta name="Copyright" content="<?= $scMetaOgSiteName ?>">
<!--Facebook-->
<meta property="og:site_name" content="<?= $scMetaOgSiteName ?>">
<meta property="og:url" content="<?= $scMetaOgUrl ?>">
<meta property="og:type" content="<?= $scMetaOgType ?>">
<meta property="og:title" content="<?= $scMetaOgTitle . '|' . $scMetaOgSiteName ?> " />
<meta property=" og:description" content="<?= $scMetaOgDescription; ?>">
<!--Next image => SGV file is best scalable-->
<meta property="og:image" content="<?= $scMetaOgImage ?>">
<!--Twitter meta-->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:description" content="<?= $scMetaDescription ?>" />
<meta name="twitter:title" content="<?= $scMetaOgTitle . '|' . $scMetaOgSiteName ?> " />
<meta name="twitter:site" content="<?= $scTwitterSite; ?>" />
<meta name="twitter:domain" content="<?= $scTwitterDomain ?>" />
<meta name="twitter:image" content="<?= $scMetaOgImage; ?>" />
<meta name="twitter:creator" content="<?= $scTwitterSite; ?>" />
<!--PintRest meta-->
<meta name="p:domain_verify" content="<?= $scPintRestKey; ?>" />
<!--Favicon meta-->
<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="48x48" href="/favicon/android-icon-48x48.png">
<link rel="icon" type="image/png" sizes="72x72" href="/favicon/android-icon-72x72.png">
<link rel="icon" type="image/png" sizes="144x144" href="/favicon/android-icon-144x144.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
<link rel="manifest" href="/favicon/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<!-- No caching -->
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />



<title><?= $scMetaOgTitle . " | " . $scMetaOgSiteName ?></title>

<link rel='icon' href='data:,' />

<!-- <link rel="stylesheet" href="css/site/home.css"> -->
<link rel="stylesheet" href="/css/<?= $scMetaPath; ?>.css">